### ISSUE TITLE
Sugestion - Games for Linux

### ISSUE THREAD

**Issue by daedric7** [axewater/sharewarez#10]
Certain games come neatly packed in a .sh file.

If a game like this is found, it could be marked as available for Linux ?

**Comment by axewater** [comment]
oh yes we can!
i have built these new features today that should support your use case.
-'my games are files' and 'my games are folders' scanning options
-multi libraries (name and platform)

the file scanner is not yet looking at .sh files, but once it does I will close this issue
pls wait for 1.2.0 to be released this weekend (I hope) with tons of new features.

**Comment by Bovive** [comment]
Do they ever come packed in different formats like .deb or is it always .sh? Appreciate the feedback, I have not done a lot of Linux gaming outside of just using Steam.

**Comment by Bovive** [comment]
@axewater can we close this out since the user can now add allowed file types?

**Comment by axewater** [comment]
yes you can now manage your filetypes and add .sh and others
