### ISSUE TITLE
Scanning Wrong Library

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#100]
1) Go to Dashboard -> Library Manager
2) Click "Scan Games"
3) Navigate to "Auto Scan"
4) Change "Select Library" to a different library.
5) It scans the original library and not the newly selected library.

**Comment by Bovive** [comment]
I think a fix of #105 would also fix this.

**Comment by axewater** [comment]
you were right, fixing #105 also fixed this!

**Comment by Bovive** [comment]
Looks great, confirmed fixed!
