### ISSUE TITLE
Game Downloads Don't Process

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#101]
Games that are scanned and added as "My Games are Files" will not download. They stick at processing. Games that are scanned and added as "My Games are Folders" works just fine.

![Screenshot_23-10-2024_223740_127 0 0 1](https://github.com/user-attachments/assets/dfa669c2-e0d0-4130-aeda-9e7809e41111)

![Screenshot_23-10-2024_22379_127 0 0 1](https://github.com/user-attachments/assets/855291c5-4db8-4f81-a133-6b02181fec1f)

**Comment by axewater** [comment]
fixed
