### ISSUE TITLE
Manual Scan Only Shows Folders

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#102]
Manual scan does not list games if they are files. It only shows subfolder names. It will add the game correctly if it is in a subfolder, but it will not work if games are sorted by files.

![Screenshot_23-10-2024_224043_127 0 0 1](https://github.com/user-attachments/assets/80c47510-c006-4107-98e2-106647ffcb62)

![Screenshot_23-10-2024_224057_127 0 0 1](https://github.com/user-attachments/assets/296916fe-069f-4d3d-9bdf-2e07d8bbb127)

**Comment by axewater** [comment]
this is mostly fixed now. i added the same selection as on the auto scan tab, the only issue now seems to be that it doesnt retain the library selection and games always get added to the first library. one thing at a time, i tried fixing this but it wasnt a quick fix.

**Comment by Bovive** [comment]
You may want to leave this ticket open. The behavior I am seeing now for identifying files is that it is not identify all extensions. Currently I am only seeing .iso, .zip, and .rar show up. The .sfc, .32x, and .nes extensions are not being detected. I have not tested other file extensions.

**Comment by Bovive** [comment]
It also pulls the name of the file in as the game name when doing a manual scan for "My Games are Files".

![Screenshot_25-10-2024_105134_127 0 0 1](https://github.com/user-attachments/assets/6314ea44-1d28-49a5-b2e6-00b11cab1b9d)

**Comment by Bovive** [comment]
In regard to the library selection not being retained, it does that on the automatic scan too. I'll open another ticket for that though as I have some info on it.
