### ISSUE TITLE
Scan Selection is Not Retained

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#105]
Automatic and Manuals scan selection is not retained after running the scan.  I'll break them down separately as they behave slightly differently. The fix is hopefully rather simple though.

**Automatic Scan**
If you navigate to the scan page using the URL ending in "scan_management?library_uuid=somelibraryid", the automatic scan pulldown will show the correct library.

Set it so that when the library dropdown is changed, the page URL is changed to match the library_uuid. 

**Manual Scan**
This page does not work the same for some reason. Ending the URL in "scan_management?library_uuid=somelibraryid" does not update the library selection.

**Comment by axewater** [comment]
think this is fixed now, can you please confirm ? @Bovive

**Comment by Bovive** [comment]
Can confirm that the selection is matching between both auto scan and manual scan. It stays when tabs are switched. Also maintains after running manual scan and auto scan. Closing issue as this appears to be resolved.
