### ISSUE TITLE
Feature Request: Notification Settings

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#106]
Admin page for notification settings. Currently there is only Discord, so options would be something like this:

**New Settings**
- On/Off for New Games (Once added to the DB, I can check this value prior to running the Discord cord)
- On/Off for Game Updates (Not implemented yet, but the value in the DB now would be helpful later)

**Move some config settings to the DB**
- DISCORD_WEBHOOK_URL
- DISCORD_BOT_NAME
- DISCORD_BOT_AVATAR_URL

**Comment by axewater** [comment]
ok i've added these to the settings panel, and they are saved to the database.
I will try add a panel for configuring the discord bot settings

**Comment by axewater** [comment]
all done in 1.4.9.4
