### ISSUE TITLE
Docker: Downloads for games are generated inside the container and are erased on restart

### ISSUE THREAD

**Issue by daedric7** [axewater/sharewarez#11]
Perhaps there should be a mount for `/app/modules/static/library/zips` so that generated downloads are kept outside the docker container and persists on restarts.

**Comment by axewater** [comment]
alright the structure is already there to support this, I actually did not get around to finishing this off.
very good submission. will attempt to resolve asap

**Comment by axewater** [comment]
this should work now. the 2 mounts are now DATA_FOLDER_WAREZ and DATA_FOLDER_IMAGES
IMAGES actually points to the library directory, of which the ZIPS are a subfolder.
