### ISSUE TITLE
Libraries Show Wrong Platform Name

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#111]
Libraries are showing the libraryplatform DB value on the list instead of the resolved name.

![Screenshot_27-10-2024_184438_127 0 0 1](https://github.com/user-attachments/assets/82a24c2c-4a92-47bd-95c7-83ca0d58fcf7)

For example, `SEGA_32X `should be `Sega 32X`.

**Comment by axewater** [comment]
fixed in 1.7.2
