### ISSUE TITLE
Delete Button After Image Upload

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#116]
After uploading a new screenshot, the delete button for that screenshot does not match the others until the page is refreshed.

![Screenshot_28-10-2024_12925_127 0 0 1](https://github.com/user-attachments/assets/2e106dce-f5cd-45d2-a81c-5547d4fd8b5d)

**Comment by axewater** [comment]
fixed ? mostly ... not sure its possible to have a way to be compatible with all the themes

**Comment by Bovive** [comment]
Close. The image container being added here is missing the class in the div element:

```<div id="image-1195">```

Should be:

```<div class="image-editor-image" id="image-1195">```

Adding the ```image-editor-image``` I believe should make it work for all themes and look the same as the others.

**Comment by axewater** [comment]
thanks!
1.6.5.1 delete image button styling
