### ISSUE TITLE
Server Settings Notification Stalks You

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#118]
It also multiplies. Check off a few server settings. Then go to another page. See something at the top like this:

![Screenshot_28-10-2024_183544_127 0 0 1](https://github.com/user-attachments/assets/ebd24422-d859-4ce7-9de5-69f3a782d3b2)

**Comment by axewater** [comment]
stalkerwarez!

**Comment by axewater** [comment]
removed flash message
