### ISSUE TITLE
Support for Update Files

### ISSUE THREAD

**Issue by The13thTimelord** [axewater/sharewarez#12]
Hi!

Firstly this project is insanely good at it's early stages! Good job on this!

I was wondering if there could be support in the Future for Update .exe files.  For example this is how I common store my games:

![image](https://github.com/axewater/sharewarez/assets/3193292/d832a1f4-d8e9-4c4f-a3ce-996de4536da2)

It would be nuce to see a "Updates" tab on the game maybe? Then it saves the application zipping up the entire game + Updates if that makes sense?

**Comment by axewater** [comment]
I have tried to design the app in a way that 'it just work', without giving users instructions on how to name their folders or files. Now of course the above feature could be transparent, and just inky work if you name your updates folder 'updates'. However, the application can also scan 'file based', some people have their games as zip files in a single folder (often ROM collections).
This would not work together with the update system. Right now if you keep your files the way they are, it will be detected as 'a folder with multiple files', and therefore be zipped up including the updates. That however cancels out the advantage I have bukilt in where it detects a single file in the folder, where it creates a direct link instead of a zip file.
Do you have any good ideas how we could implement updates?

**Comment by Bovive** [comment]
This is a big feature that would be incredibly useful. It would be what would really set this apart from Gamevault. I think you could do this by:

1) Do not make folder searches recursive for the main game. Different platforms can have different libraries. This means just a simple folder structure of one folder per game. 

2) Let the user specify the common name they use for their update subfolders. This could be an option. If specified, it will be listed as separate update files for download. If not, works as it currently does.

3) It may also be nice to allow an optional "Additional Files" folder designation. Some files for the game may not be updates.

I think that zipping files in an updates folder would be troublesome to a degree. The scanning/zipping of an updates folder should work like this:

- If it is a an .exe or compressed file, list it individually.
- If it is a subfolder of the updates folder, go ahead and zip that subfolder and name it as the subfolder title. Some updates are multiple files and placed in its own folder. This solves that issue.

Putting it all together in one zip means downloading the main game that may be very large just to get a very small update file. In addition, the user doesn't know there is an update file even available. I will also note that the way it currently works it doesn't zip subfolders with a main game file that is already a compression file. For example, the Alan Wake image the OP has would only provide the iso file and not zip it all together. At least that is how it is working for me. 

This method would also provide a working foundation for a future notification system such as Discord webhooks for when an update is available.

**Comment by axewater** [comment]
alright I see how it could be done .. will look at this

**Comment by Bovive** [comment]
If this is added, I can make a Discord notification for updates being made available as well. I'd like to be able to add a Discord notification for if the main game file is changed as well, but that would require some kind of file scanning to detect file changes.

**Comment by Bovive** [comment]
Thank you @The13thTimelord for this feature request. I have completed this feature and submitted a PR. It is currently undergoing testing. It works as you described with two small caveats:

1. There is also a folder for "Extras" that you can define. This is for files that don't fit as updates, but you want to be downloadable.
2. The game does not download with the updates included. They must be downloaded separately. I'll be honest, I didn't notice that part of your request until now. If it is a truly desired feature, I can take a look at how to implement that option.

I hope that you like what we have come up with. In the near future I will look at implementing Discord notifications for when update files are added. For now it only works with the main game file. Let me know if you have any suggestions on tweaking this once it goes live. Thanks!

**Comment by Bovive** [comment]
Closing this out as it is now complete.
