### ISSUE TITLE
Better Unmatched Results

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#124]
I think that something worth looking at is better unmatched results. In that speaking, more game result in being unmatched. The way that the IGDB API results game matches is subpar and affects more than just SharwareZ. Perhaps comparing the file name (minus extension) to the name of the game it first matches with could help. If not within 90% of being the exact same, push it to unmatched so that it can be matched manually. I would rather manually match an unmatched game than fix one that matched incorrectly.

**Comment by axewater** [comment]
I agree the matching needs improvement. The only time I really get incorrect matches, is if the game already existed in my database, then it fallsback on an alternative match. Can you provide examples of games that are matched incorrectly ?

**Comment by axewater** [comment]
btw I mainly test with PC DOS and PC Windows games ... igdb seems to do well at that. The roms I added later when I found out it could match those decently as well. But the roms database on igdb is very incomplete, I get missing games (no match at all, even manually).

**Comment by Bovive** [comment]
Mostly PC for me too. Above Snakes is a good example.

**Comment by axewater** [comment]
talked to the ppl from IGDB .. improivements will be made on their end
