### ISSUE TITLE
Add Subfolder Support

### ISSUE THREAD

**Issue by JamesRy96** [axewater/sharewarez#125]
I'd love to see better support for subdirectories in the library, currently all games within a subdirectory are viewed as one "game" instead of individual games. If you add the subdirectory as a library location the individual games do load as expected. 

Example file tree:

/media/seagate/Software/Games/Jackbox/
├── Jackbox Party Pack 2
├── Jackbox Party Pack 3
├── Jackbox Party Pack 4
├── Jackbox Party Pack 5
├── Jackbox Party Pack 6
├── Jackbox Party Pack 7
├── Jackbox Party Pack 8
└── Jackbox Party Pack 9

All of these games were grouped together under "The Jackbox Party Pack" originally.

**Comment by Bovive** [comment]
This may be possible if we go one deeper on the subdirectory scan for "My games are a folder". We would need to exclude scanning extra and updates folders.

The issue I see with this however is that an uncompressed game could be in that folder and we would end up scanning subdirectories for game files.

Perhaps we could check if the folder only contains subfolders and no other files and if so then treat it as a collection and scan the subdirectories as game folders. I imagine that would resolve any issues and be the easiest solution.

**Comment by axewater** [comment]
this is going to be a mess and will not be easy to explain to users how to build their library
