### ISSUE TITLE
Feature Request: Debug Log

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#13]
It would be nice to have the option to produce a debug log. Right now I cannot see any errors when they occur.

Edit: I see that some things need to be uncommented in the code to see the debug. Perhaps a toggle setting could be used. I did not see any SMTP errors using the Docker image. That made it rather difficult to track down why the mail handler was not working.

**Comment by axewater** [comment]
its already running in debug mode by default, can you be more specific about which errors you would like to see printed ?

**Comment by Bovive** [comment]
It was SMTP errors not showing when setting up the email config that I noticed it. I assume there is no debug for that. I also did see some debug lines commented out. Not sure if they could be toggled or not or if they actually do anything:

routes.py

```
# print("Request method:", request.method)  # Debug line
# print("Form data:", form.data)  # Debug line
# print("Request method:", request.method)  # Debug line
```

utilities.py

```
# print(f"DEBUG Committing changes to database (1).")
# print(f"DEBUG Committing changes to database (2).")
# print(f"DEBUG Committing changes to database (3).")
# print(f"DEBUG Committing changes to database (4).")
```

**Comment by axewater** [comment]
added configuration checks and connection testing in SMTP routines.
not thoroughly tested
