### ISSUE TITLE
Discord Setting Do Not Import

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#131]
The Discord settings from config.py do not import into the database upon first run. They also are not used.

**Comment by axewater** [comment]
great then we can remove them there. lets get as much out of the config.py as possible.
we'll make an initial setup procedure where the user can fill everything in to get things up and running.

do you agree ?

**Comment by Bovive** [comment]
I think that is a good idea. It would be nice to get everything out of the config that doesn't need to be there.

**Comment by KrystoferRobin** [comment]
Just came to report on this

still isn't working

set in config and through the site - still nothing.  Error says the webhook isn't set, I'll get the exact error and attach.

**Comment by Bovive** [comment]
I'm actually working on this at the moment. I'll submit a PR to move everything from the config file to the admin panel shortly.

**Comment by Bovive** [comment]
Whenever my pull gets merged and the Docker container is updated you should be able to set the Discord settings solely in the Admin Panel. Let me know if you have any issues after that. You are welcome to try the bovive/sharewarez:latest image if you like. It's a development version but should be mostly stable. You can always switch back to the official image, it shouldn't affect anything.

**Comment by KrystoferRobin** [comment]
I was fiddling with your docker for a bit, then back to mainline, then just ran it on bare because the docker is behind, and so many things are broken/not-configurable.  For the time being, I'm just running it via python3 app.py
