### ISSUE TITLE
Profile Page Invites Wrong

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#140]
The invite count on the user profile page does not take into account sent but unclaimed invites. It should match that on the user invites page.

Invites Page:
![Screenshot_30-11-2024_18516_localsharewarez czerkacorp com](https://github.com/user-attachments/assets/a7e2b46a-599a-4eb3-a40b-5fc0f6b610d9)

User Page:
![Screenshot_30-11-2024_185056_localsharewarez czerkacorp com](https://github.com/user-attachments/assets/db96056f-836f-42d1-ab89-6567586ed658)

**Comment by axewater** [comment]
fixed 1.6.1
