### ISSUE TITLE
Scanning hung - will not cancel

### ISSUE THREAD

**Issue by KrystoferRobin** [axewater/sharewarez#141]
Using automatic folder scan

select a library
"My games are files"
select path
Start On-Demand Scan

says running, flashing bar at the top of the screen saying it's running.

hangs up at 52 total files/folders, 8 found, 0 failed.

Sat that way for half an hour, no progress.  

Clicked "Cancel Scan"

Confirmation in flashing bar across the top of the screen, table shifts to Manual Scan - switch back to Auto Scan tab - scan is still running.

**Comment by KrystoferRobin** [comment]
I did try restarting the docker and the scan is still "running" after reload.

Perhaps there's a more... firm way.. to instruct it to actually, for real, stop the scan?

**Comment by Bovive** [comment]
Hey, thanks for the report. First off, let's get you fixed and running again. The automatic scan jobs are stored in the Postgres database. You'll need to delete that entry and then it will go back to normal. Personally, I use pgAdmin 4 to edit the database so my screenshots are based on that.

It will be at YourDatabase -> Schemas -> Public -> Tables -> scan_jobs

<img width="229" alt="Tables" src="https://github.com/user-attachments/assets/53da8cca-c1d4-49c0-bfc6-b88710baf34e">


Right click on scan_jobs -> View/Edit Data -> All Rows

Here you will find your current stuck scan job. It probably won't be ordered by time, so look for the one with the "status" of running (I think thats what it is, it wont be completed anyway). 

Select the row for that entry. Click the "Delete" button. Then click the "Save Data Changes" button.

<img width="689" alt="Delete" src="https://github.com/user-attachments/assets/ebb89e9a-9095-4942-88cc-58929e8ffdbb">

That should let you run a scan again. You can do this while the Docker container is running or stopped, but probably better to stop it first and start it again after you delete the entry. 

As to why this occurred, I am not sure. You can try another scan and see if it also hangs. If so, you can always delete the DB entry again. The Docker image is a bit behind development. I cannot recall if this was an issue identified and resolved since then. What version of SharewareZ are you running?

If it keeps hanging, we can investigate further. Thanks!

**Comment by KrystoferRobin** [comment]
version 1.5.1

I did give it a good sporting try to not use the docker, because the docker has so many issues - but that was a couple hours of frustration that ended in a non functional install.  I was able to beat the docker compose into shape, get running, and adding things to the libraries.  Finding weird behavior here and there - removed an entry and now there's a permanent missing/blank space, the hanging scan, etc.  I'll report anything I can't fix myself.

To the point - learned enough psql to be dangerous, nuked the offending scan, doublechecked my directory was clean of any weird junk (my mac likes to leave little droppings all over the NAS).  now that I've nuked all the ._[filename] from the directory (there was a single one) the scan gets further, but stalls after 15 id's instead of just 8.

Is there anything with file naming that needs to be considered?

**Comment by Bovive** [comment]
Are you adding your games as a file or as a folder when you scan? Extensions matter for detection purposes, but it shouldn't hang a scan. Do the logs provide anything when it hangs? Should be output on the Docker console. Perhaps it will tell you what file/folder it is hanging on.

**Comment by KrystoferRobin** [comment]
I started by adding my GoG library - which is 1 folder = 1 game
Worked near-flawlessly.  Had a few mis-id's and a few duplicates to sort out, nothing major, over 800 games scanned.

Adding a bunch of zips now, as "My games are files" instead of "my games are folders" and it's hanging up.  They are all .zip, and there's just 51 files in that particular directory.

docker logs shows a spam of repeating the same two lines - hundreds over the last 4-5 minutes of just letting it run for a while.

172.23.0.1 - - [01/Dec/2024 19:16:41] "GET /api/scan_jobs_status HTTP/1.1" 200 -
172.23.0.1 - - [01/Dec/2024 19:16:41] "GET /api/unmatched_folders HTTP/1.1" 200 -

**Comment by KrystoferRobin** [comment]
Correction, there does seem to be something other than just sitting there.  I was using > log.txt so I could easily view the output, but I really needed &> log.txt to get all of it.

Attaching here.
[log.txt](https://github.com/user-attachments/files/17970099/log.txt)

**Comment by Bovive** [comment]
You should receive a lot more output on the console as it processes the games and grabs the IGDB metadata. Those two lines in the log are just the page refreshing the data because you are on it. If you navigate away from that page it should stop.

Looking at your log here is the error:

```During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/ctx.py", line 184, in wrapper
    return ctx.app.ensure_sync(f)(*args, **kwargs)
  File "/app/modules/routes.py", line 1124, in start_scan
    scan_and_add_games(full_path, scan_mode, library_uuid)
  File "/app/modules/utilities.py", line 1106, in scan_and_add_games
    scan_job_entry.folders_failed += 1
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 803, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1670, in load_scalar_attributes
    result = load_on_ident(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 509, in load_on_ident
    return load_on_pk_identity(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 694, in load_on_pk_identity
    session.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2237, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2106, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 973, in _raise_for_prerequisite_state
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "games_slug_key"
DETAIL:  Key (slug)=(dungeon-dungeon) already exists.

[SQL: INSERT INTO games (uuid, igdb_id, name, summary, storyline, aggregated_rating, aggregated_rating_count, cover, first_release_date, rating, rating_count, slug, status, category, total_rating, total_rating_count, url_igdb, url, video_urls, full_disk_path, date_created, date_identified, steam_url, times_downloaded, nfo_content, developer_id, publisher_id, file_type, library_name, library_uuid, size) VALUES (%(uuid)s, %(igdb_id)s, %(name)s, %(summary)s, %(storyline)s, %(aggregated_rating)s, %(aggregated_rating_count)s, %(cover)s, %(first_release_date)s, %(rating)s, %(rating_count)s, %(slug)s, %(status)s, %(category)s, %(total_rating)s, %(total_rating_count)s, %(url_igdb)s, %(url)s, %(video_urls)s, %(full_disk_path)s, %(date_created)s, %(date_identified)s, %(steam_url)s, %(times_downloaded)s, %(nfo_content)s, %(developer_id)s, %(publisher_id)s, %(file_type)s, %(library_name)s, %(library_uuid)s, %(size)s) RETURNING games.id]
[parameters: {'uuid': 'bf75b74b-c1ab-4c21-8a43-d14bf5cd4475', 'igdb_id': 224631, 'name': 'Dungeon Dungeon!', 'summary': 'Dungeon Dungeon! is a turn-based RPG with roguelike elements and a loot system. Recruit companions, upgrade skills, collect loot and build up your team to conquer the dungeons!', 'storyline': None, 'aggregated_rating': None, 'aggregated_rating_count': None, 'cover': None, 'first_release_date': datetime.datetime(2023, 9, 22, 0, 0), 'rating': None, 'rating_count': None, 'slug': 'dungeon-dungeon', 'status': None, 'category': 'MAIN_GAME', 'total_rating': 1.0, 'total_rating_count': 1, 'url_igdb': None, 'url': 'https://www.igdb.com/games/dungeon-dungeon', 'video_urls': 'https://www.youtube.com/watch?v=w6dpFwFwBzU', 'full_disk_path': '/storage/smutty/Dungeon.Vixens.A.Tale.of.Temptation.zip', 'date_created': datetime.datetime(2024, 12, 1, 19, 20, 54, 610954), 'date_identified': datetime.datetime(2024, 12, 1, 19, 20, 54, 610958), 'steam_url': '', 'times_downloaded': 0, 'nfo_content': None, 'developer_id': None, 'publisher_id': None, 'file_type': None, 'library_name': None, 'library_uuid': '9ad6c994-af23-4ef7-a26d-04cd255c3d9d', 'size': 214733254}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)```

I have not worked on this part of the code so I'm a bit unfailiar, but I think that it is trying to add a game (Dungeon.Vixens.A.Tale.of.Temptation.zip) to the database that already exists. It looks like it was unable to match it on IGDB. On the scan page does it show up in the "Unmatched Folders" tab? 

@axewater any insight on this?

**Comment by KrystoferRobin** [comment]
It does show up in the unmatched as a DUPLICATE.  

Just as a quick sanity check 
- I removed that entire library, and recreated it with a different name.
- I moved each file into it's own folder, I did not extract them.  I noticed it's checking inside the zips for NFO's, not sure if it does that on a Game As Folder scan, but figured maybe it doesn't, so I'm running that scan now to see if it also hangs up or not.

--hung up on dungeon vixens again

--- removed dungeon vixens and scan was able to complete without issue (aside from a lot of missing igdb entries, most of these shovelware adult titles seem to not have entries - I'll just manually populate them until we have other options for metadata scraping)

The file unzipped just fine, but just wouldn't scan for some reason.  Other entries were duplicates and didn't halt progress, I'm guessing the db entry for that one is screwy somehow.  I do not have a way to visually navigate my db so I can't really poke around in there easily.  gotta do it via console and that's mega feelsbadman.

**Comment by Bovive** [comment]
Check out [pgAdmin](https://www.pgadmin.org/download/pgadmin-4-windows/). It is free and a wonderful UI tool for Postgres. I run it in Docker but I believe it also has a standalone client.

Glad that it got you going. I agree, IGDB doesn't match all that great for a lot of titles. It's something I'd like to work on as an improvement or at least filter out ones that don't auto match correctly. As far as the error, from what I can tell it seems to want to add dungeon-dungeon as a value to the slug column in the DB but it's a unique key and so it cannot duplicate. In the games table of the database, are any games matched to a value of "dungeon-dungeon" in the column called "slug"? Deleting that row may fix it. However, if the game in that row is mismatched then you may be able to fix it by matching it correctly. I honestly do not know where that value comes from but here are the culprit lines from your log:

```
violates unique constraint "games_slug_key"
DETAIL:  Key (slug)=(dungeon-dungeon) already exists.
```

**Comment by KrystoferRobin** [comment]
I couldn't get pgAdmin to connect remotely and it was harder to figure that out than to just exec into the docker and do it by hand :D

As such, I cannot effectively navigate the tables currently to sniff for dungeon-dungeon.  But I know that one actually came up mis-matched to another game, which I corrected - perhaps it left behind a messy entry or something.  I'm about "I guess I'll learn postgresql this weekend"'d out though so that will have to wait until I feel inspired to dig harder.

**Comment by Bovive** [comment]
Ya, Postgres is picky in that it will only allow localhost connections unless you tell it otherwise. Good instructions [here](https://www.bigbinary.com/blog/configure-postgresql-to-allow-remote-connection) on how to do that if you are so inclined. I'll leave the ticket open so that @axewater can take a look at the logs. Let me know if you need any further assistance.

**Comment by KrystoferRobin** [comment]
It originally gave Dungeon-Dungeon to Dungeon siege.  After correcting that
entry it still showed up as Dungeon-Dungeon in the db itself (which I
finally have access to with pgAdmin!).  I have corrected quite a few
oddball entries, and upgraded to 1.6

I haven’t had anymore scans hang up, but if and when they do I’ll grab logs
again, and for any other issues I run into that I don’t think are user error

**Comment by axewater** [comment]
I created 2 folders, dungeon siege and dungeon vixens
it made a mess of things :) it finds dungeon siege III and then cant find dungeon vixens, so ends up looking for 'dungeon' and matching it to a game called dungeon dungeon!
this is just bad matching, not really a lot I can do without applying AI (which would cost money) the IGDB API is just not great.
I will do some more testing to see if I can improve it somehow

**Comment by axewater** [comment]
> I did try restarting the docker and the scan is still "running" after reload.
> 
> Perhaps there's a more... firm way.. to instruct it to actually, for real, stop the scan?

updated docker config and app a little here and there .. you could try the docker again.

**Comment by KrystoferRobin** [comment]
> I created 2 folders, dungeon siege and dungeon vixens it made a mess of things :) it finds dungeon siege III and then cant find dungeon vixens, so ends up looking for 'dungeon' and matching it to a game called dungeon dungeon! this is just bad matching, not really a lot I can do without applying AI (which would cost money) the IGDB API is just not great. I will do some more testing to see if I can improve it somehow

Yeah, their api is dodgy - if it fails to find something, I go to their site and just search there, about half the time I find the game, copy the ID number, and *then* the api can find it.  It's a bit silly really, and seems to be a difference between how the api and how their on-site search differ.

If this hangup is really caused by poor matching, perhaps adding additional fallback search api's, or decoupling the requirement to have a game located on igbd to add it to a library would be a higher priority than before?

MobyGames requires a subscription to access their API, but some of us have one already for our rom managers/etc.  If you don't have access to it, set up a kofi or something and I'll pay for your sub so you can figure out how to hook it in as an option.  I know over on reddit a bunch of people were throwing shade like "what problem does this solve" - well I'll tell you - it's *exactly* what I was looking for, so anything I can do to help to make it the best solution "to a problem no one has" - I will.  Sadly, code is all gibberish to me, or I'd start trying to help with that.

**Comment by Bovive** [comment]
The IGDB matching is a problem for pretty much anyone that uses it. Gamevault and Retrom match incorrectly just as our does. That being said, I would like to research how to handle it better and we have discussed it some already. I would like if the game folder/file name does not match the title name (case insensitive and all special characters removed) to throw it at a queue that needs to be manually matched. This would also help avoiding Discord notifications being sent out for mismatched games. I think the fuzz Python library would also allow us to use fuzzy string matching so we could compare the names by a percentage match instead of a direct match (like if not 90%+ match go to manual verification).

But anyway, I'm getting pretty off topic for this post. I probably should just create a feature request for this.

**Comment by Bovive** [comment]
Can we close this out @axewater?
