### ISSUE TITLE
Curations

### ISSUE THREAD

**Issue by KrystoferRobin** [axewater/sharewarez#142]
Since we cannot have duplicated entries, it would be nice to have a way for users to curate a list of favorites/recommendations/games running on the same engine, etc.

**Comment by Bovive** [comment]
Something similar to #49?

**Comment by KrystoferRobin** [comment]
Ah, yes!  Just a way to have secondary lists compiled from the libraries as "I've played these" "I want to play these" "Hey friends, you should try these" etc.
