### ISSUE TITLE
No Logo on Help Page

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#25]
The site logo does not show on the help page.

![helppage](https://github.com/user-attachments/assets/f757575b-b6f4-4e76-bb0e-bea288ce2b75)

**Comment by axewater** [comment]
sigh .. i tried cleaning up the routes file by splitting it into other files. i had to move it back because if I try to apply the same context processor I get import loops and I have no idea how to solve it :)
but the issue above is resolved.
