### ISSUE TITLE
Popup Not Disappearing

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#26]
If you move your mouse cursor over a cover image and then quickly off, the popup will not go away. I suspect it has not finished the onmouseover event before the onmouseout event would be fired. Maybe we need to add "onmouseout="hideDetails()" to parent div elements?

**Comment by axewater** [comment]
sorry is pent a ton of time on this, and cant solve it ... its too hard to reproduce too. if you can find a consistent way of triggering this bug, I will have another go at it

**Comment by Bovive** [comment]
I am attaching a screen recording of how to reproduce it. Watch the mouse cursor. It's all about how fast the mouse cursor is moved onto and off the game cover. It only occurs when it is done quickly. 

https://github.com/user-attachments/assets/9590d08e-34e9-4cef-8541-66828c2719d4

**Comment by Bovive** [comment]
I was able to find a fix. Incoming PR.

**Comment by axewater** [comment]
fixed it like boss he did
