### ISSUE TITLE
Wrong Game Size

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#27]
If the game file size is less than 1 MB, it will show as 0 MB on the game details page and the popup page. This is most noticed with ROM files which are quite small. Probably could be added to filters.py as an additional else if statement.

**Comment by axewater** [comment]
roms were added as an afterthought :) i was just organizing my windows games at first. filesizes are stored in megabytes in the database, so a lot of roms are 0.0 , so its not a filtering issue. i did run into redundant code when looking at filters.py it was not actually used at all, thats now removed.
i'm looking at fixing this at the source, it means we will go to a new database model, need to store the size differently

**Comment by axewater** [comment]
now completely fixed.
game sizes are now stored in number of bytes and this is converted to human readable (including KB now)
you will have to rescan your library
