### ISSUE TITLE
Failed Game Requires Refresh

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#28]
If a folder/game fails during a game scan it shows up under the "Unmatched Folders" tab on the scan_management page. If you click on the "Unmatched Folders" tab it will not show until you refresh the page.

Steps:

1) Start a scan that results in a failed folder.
2) Let the scan finish and do not navigate away from the page.
3) Click on the "Unmatched Folders" tab.
4) Failed folder does not appear.
5) Click refresh on your browser.
6) Now it appears.

Perhaps there is an html or java command that could force refresh the page when that link is clicked? The better option might be to have the unmatched folders result auto refresh.

**Comment by axewater** [comment]
implemented
