### ISSUE TITLE
Cannot Match Unmatched Folder

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#29]
Folder was unable to match after scan. Put in the IGDB ID and it pulled all the info into the fields. Unable to save it however. Gives the error "This Field is Required" but doesn't say which field. Nothing in the logs. I do not see a field missing that should be required.

![fieldisrequired](https://github.com/user-attachments/assets/5941a722-fce1-407b-8a56-cacdce7c5630)

**Comment by axewater** [comment]
this was broken after I added 'libraries' as a feature ... fixed now!

**Comment by Bovive** [comment]
Confirmed worked, thanks!
