### ISSUE TITLE
Increased Page Size and Sort by Console

### ISSUE THREAD

**Issue by kavg13** [axewater/sharewarez#3]
Love what you created here and it helps organizes my collection wonderfully! 

Would you be able to increase the "games per page" to like 500 or 1000? 100 seems rather small and still causes me to sort through multiple pages.

Also would be cool if you added in the ability to sort by Console (Playstation, Gamecube, Xbox, PC, etc).

Keep up the great work!

**Comment by axewater** [comment]
I updated the library_browser.html to include options for 500 and 1000 per page. Performance still seems fine on my machine, please let me know if you have any issues!

As for you second question, can you please open a new issue, and explain more in detail what your end goal is ?
To implement a filter that shows only the titles that 'exist on that platform' is easy, we have that data already. But i'm not sure that's what you want.

**Comment by axewater** [comment]
I have added a user preferences panel where you can save your default 'per page' and sort options.
unfortunately you will have to reset your database if you run the old version, or do a database migration yourself
