### ISSUE TITLE
Sometimes Wrong Games Show in Wrong Library

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#30]
When clicking on an individual library from the discover page, sometimes it will load games that are not from that library. It seems that perhaps sometimes the filter is being applied before the games have finished loading. Clicking the apply button does filter it down correctly. It does not happen every time, but it does happen often.

**Comment by axewater** [comment]
shit that is a weird ass error. man this was the first app I ever coded :) i did some weird things. inconsistent, so probably harder to figure out, but seems like a serious issue, will prioritize.

**Comment by Bovive** [comment]
It might be fixed by somehow increasing the apply filter delay. I honestly didn't look at the code at all.
