### ISSUE TITLE
Feature Request: Discover or Home Option in Sidebar

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#32]
Currently the only way to access the Discover page is to click on the site logo in the top left. If the "Show System Logo" option is disabled, there is no link to access the Discover page. You can access it by logging out and then back in, but that seems tedious.

![Sidebar](https://github.com/user-attachments/assets/513f4bcf-99a6-4547-bdda-ba64b183358b)

**Comment by axewater** [comment]
added to the sidebar
