### ISSUE TITLE
Feature Request: Option to Disable "Delete Game on Disk"

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#33]
On the Server Settings page it would be nice to have the option to enable/disable the "Delete Game on Disk". I believe it should be disabled by default. Could prevent some accidental deletion by the admin. 

![ServerSettings](https://github.com/user-attachments/assets/c418b8e7-a7a3-4b99-a25f-6f92b23c83bf)

![removegame](https://github.com/user-attachments/assets/d9444db0-44d4-422c-8daa-300c56103946)

**Comment by axewater** [comment]
i made it enabled by default, but otherwise implemented as suggested.
