### ISSUE TITLE
Feature Request: Browse Folder Path Show All Drives

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#34]
For Windows deployments the "Browse Folder Path" button on the Scan Management pages will show the root of drive configured in config.py ()

Default:
`BASE_FOLDER_WINDOWS = os.getenv('BASE_FOLDER_WINDOWS', 'C:')`

It would be nice to be able to display all drives and network drives. This might require using Python 3.12 and accessing the new os.listdrives() or os.listmounts() functions ([Reference](https://docs.python.org/3/library/os.html)).

**Comment by axewater** [comment]
cant fix this in the way the app is designed
