### ISSUE TITLE
Settings BASE_FOLDER_WINDOWS to Drive Installed on Breaks "Browse Folder Path" Button

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#35]
If hosting on Windows the drive to set as root for the "Browse Folder Path" buttons on the Scan Management pages is set in the config.py as:

Default:
`BASE_FOLDER_WINDOWS = os.getenv('BASE_FOLDER_WINDOWS', 'C:)`

If the app is installed on the same drive that is set for BASE_FOLDER_WINDOWS it will show the app directory as root when clicking the "Browse Folder Path" button:

![BrowseFolder1](https://github.com/user-attachments/assets/4d9765bf-ff60-4b50-a4d6-9028cebba650)

If you click on a folder such as "venv" and then click the "Up" button it does take you to the drive root and functions correctly from there.

If the config is set to "/" it will show the root of the drive installed on: 

`BASE_FOLDER_WINDOWS = os.getenv('BASE_FOLDER_WINDOWS', '/:)`

However, it will not function correctly. It will propagate the folder clicked on but will not show any subfolders.

Setting the option to a drive that the app is not installed on works fine.

If you change the BASE_FOLDER_WINDOWS to include a trailing '/' it works correctly and shows the drive root as expected:

`BASE_FOLDER_WINDOWS = os.getenv('BASE_FOLDER_WINDOWS', 'C:/)`

Long writeup to say to change the default config to be:

`BASE_FOLDER_WINDOWS = os.getenv('BASE_FOLDER_WINDOWS', 'C:/)`

instead of:

`BASE_FOLDER_WINDOWS = os.getenv('BASE_FOLDER_WINDOWS', 'C:)`

**Comment by axewater** [comment]
thanks for full explanation. and thanks for all your other submissions. I have some time this weekend, going to work on some of these. I will also have another go at cleaning up the routes.py file which is way too long.

**Comment by Bovive** [comment]
No problem. I think it is ok as is, just an update to the config instructions would be ok.

**Comment by axewater** [comment]
fixed as proposed .. thanks again!

**Comment by Bovive** [comment]
I must had been wrong, or it changed somehow. Now 'D:/' is not working. It just works like '/' and does not allow you to access any folders.
