### ISSUE TITLE
Feature Request: Show Last Scan Job at Top

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#36]
On the Scan Management page it currently shows the latest scan at the bottom of the list. It would be nice to see the latest at the top of the list by default. In a long list of scans it requires scrolling to monitor. Sorting options might be nice, but not necessary.

**Comment by axewater** [comment]
fixed in the js

                   // Sort the data array to ensure the latest scan is at the top
                    data.sort((a, b) => new Date(b.last_run) - new Date(a.last_run));

**Comment by Bovive** [comment]
Awesome, thanks! I'll check it against mine. I've been working on some UI adjustments, and I want to make sure I can match you.
