### ISSUE TITLE
Feature Request: Add Details to Server Settings

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#37]
It would be nice to have a detailed explanation of what each setting does on the Admin Settings page.

![Settings](https://github.com/user-attachments/assets/64791b49-3b71-4568-9ad9-90a2b42e8ff2)

Might be nice to categorize them as well such as "Users", "Games", "Server", etc. This would especially be helpful if more options are added in the future.

**Comment by axewater** [comment]
tooltips added, will also remove non working functions for now :)
