### ISSUE TITLE
Adjusted UI

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#38]
This is a proposition. I have spent a great deal of time working on a more modern UI and fixing some issues that resulted in clipping and overlap. I aimed to find a theme that felt more modern. I have a branch already for it, but I don't want to put in a pull request without approval or feedback. If there was a theme system in place it might work as that, but it touches more than just the CSS. I am attaching some screenshots for review:

New Discover Page:
![Before](https://github.com/user-attachments/assets/762783df-db43-46e6-84e7-18c36b319f65)

Game Details Before:
![Game Details Before](https://github.com/user-attachments/assets/7049610c-9f10-4597-b7f1-6c6d224dc730)

Game Details After:
![Game Details After](https://github.com/user-attachments/assets/46ae666e-0eea-4f82-8028-c62283ca27b7)
Note: I am leaving some room for future information such as file updates, etc.

Libraries Before:
![Libraries Before](https://github.com/user-attachments/assets/1d6e82da-8d48-4c8d-9f8f-7513028e10e3)

Libraries After:
![Libraries After](https://github.com/user-attachments/assets/c9266f3d-1fdc-4c5e-802b-a2330be9409c)

Scan Manager Before:
![Scan Manager Before](https://github.com/user-attachments/assets/7797e59f-4d3b-48a9-9874-644b86eb52c3)

Scan Manager After:
![Scan Manager After](https://github.com/user-attachments/assets/49b3116f-f26a-4293-8277-67223383da9a)

Screenshots Before:
![Screenshots Before](https://github.com/user-attachments/assets/fed6381a-6511-42c4-b456-f4277f73bca4)

Screenshots After:
![Screenshots After](https://github.com/user-attachments/assets/d0cc5b0e-6da7-42de-91ac-3d6c88464df1)

I would have included these in a discussion rather than an issue, but there is no discussions for this repo. Also available to discuss via Discord if you prefer. Thanks!

**Comment by axewater** [comment]
very cool work !!!! the new discover page is much better, the screenshots page as well. the game details page is very widescreen oriented, not so sure about that yet. hmm ... choices choices :)
Since your design breaks away from my beloved rounded corners, I will need to implement a theming option, which I wanted from the start. Not sure how best to handle that .. will research first.

i have enabled discussions as well, and I'm AceHighness#8917 on Discord, feel free to hit me up.

**Comment by Bovive** [comment]
Cool. I'll go ahead and close this out and start a discussion.
