### ISSUE TITLE
Cannot Ignore Unmatched Folder

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#46]
Clicking "Ignore" on an unmatched folder refreshes the page but it doesn't ignore the unmatched folder. "Clear Unmatched" also does not work. Clearing unmatched gives a toast error of "An error occurred while deleting unmatched folders". I will note that I did not click the button to delete the folder.

**Comment by axewater** [comment]
this one sounds really messed up. looking forward to seeing what I did there. (these functions worked at some point, i'm learning the hard way why people make unit tests)

**Comment by axewater** [comment]
the ignore button seems to work fine for me. it sets the status to 'ignore' which means its excluded from any scans from now on. 
identify also works from the unmatched folder list.
clear all also works.
clear unmatched gives me an error!
delete folder refreshes page but does nothing!

diving in now

**Comment by axewater** [comment]
all fixed (this was a real mess)
