### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by Ronald-Diemicke** [axewater/sharewarez#5]
Might I suggest publishing a roadmap of where you want this to go with features for the short, mid and long term?

I've got a bunch of ideas, but not where where this could end up.
Ex. 
- I'd love to see some sort of save syncing with a cloud provider / server.  
- A Lutris plugin could be tremendous.
- Maybe some sort of native client side app with cross platform support to help with mounting ISOs or running installable files (could pkg a manifest with the game on the server end to tell the client what to do?)
- ProtonDB integration ? ( I see the steamdeck as a big potential winner here for this )
- Sync Up GOG account ( these games are DRM free, so this makes a ton of sense to act as a relay [sync gog acct to server, then make the download file entries shareable with friends and family - then let them download and install to the client ?])

I'm sure there's other stuff I'm not thinking of atm...

**Comment by axewater** [comment]
alright. i guess i can use the github wiki to keep track of the roadmap. (stay tuned)
some features, like the ones you mention may walk the line of ethics a little, DRM free does not equal a license to share in all cases. But I'm all about being inclusive so the least I can do is provide some type of plugin support that would enable these types of features.

**Comment by axewater** [comment]
https://github.com/axewater/sharewarez/wiki/SharewareZ-Roadmap
