### ISSUE TITLE
base.html calls for invalid style sheet.

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#62]
base.html

Code:

```
<link rel="stylesheet" href="{{ url_for('static', filename='css/' + current_theme + '/style.css') }}">
```

Error:

<img width="425" alt="error" src="https://github.com/user-attachments/assets/3ed722cb-647c-40ab-b777-68fd09f31c50">

**Comment by axewater** [comment]
it should be :
    <link rel="stylesheet" href="{{ url_for('static', filename='library/themes/' + current_theme + '/css/style.css') }}">


and there is a css file there in a default theme folder.

are you sure you are running the latest version?

**Comment by Bovive** [comment]
Pulled from your main repo. There is no default themes folder.

**Comment by Bovive** [comment]
Looks to be fixed now.
