### ISSUE TITLE
Docker Variables?

### ISSUE THREAD

**Issue by Klages** [axewater/sharewarez#7]
Is there something else to configure than port 5001? My container always exits with code1.

**Comment by axewater** [comment]
The docker only works if you 'compose', it will run 2 containers. The
environment file is copied from the example on GitHub.

**Comment by Klages** [comment]
Ah, my bad! Was looking only in the readme. Thank you!

**Comment by Klages** [comment]
Ah, my bad! Was looking only in the readme. Thank you!
