### ISSUE TITLE
No Notification for Download

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#76]
When you click to download a game, you get the toast message "Your download request is being processed. You will be notified when the download is ready."  but there is no notification for when the download is ready. The toast message also never goes away, unless navigating away from the page or refreshing.

![Screenshot_6-10-2024_105154_127 0 0 1](https://github.com/user-attachments/assets/aea7b369-1539-40dd-9058-f6075d8b754e)

**Comment by Bovive** [comment]
Also worth noting that you have to refresh the page for the download button to work.

**Comment by axewater** [comment]
all above fixed in 1.4.9.2
