### ISSUE TITLE
Game Screenshots Incorrect for Editing

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#77]
Adding a screenshot to a game works, but it does not show up on the list of screenshots for "Edit Images".

Steps:

1. Go to a game and click "Edit Images".
2. Upload a new screenshot.
3. Notice that it is not in the list of game screenshots on the current page (edit images). Also there is no notification on this page that the upload was successful.
4. Click back button to return to game page.
5. Toast notification appears saying that upload was successful. New screenshot is visible.
6. Go back to "Edit Images".
7. Screenshot that you uploaded is not in the list of images.

This also makes it impossible to delete an uploaded screenshot.

**Comment by axewater** [comment]
all but notification fixed
