### ISSUE TITLE
Notification for Image Upload Appears on Wrong Page

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#78]
Uploading a cover or screenshot does not notify you that it was successful on the "Edit Images" page. Instead, it appears when you navigate away from that page.

**Comment by axewater** [comment]
fixed in 1.4.9.1

**Comment by Bovive** [comment]
It does now appear on the edit images pages correctly. It does however still post the old alert message when you navigate to another page.

![Screenshot_28-10-2024_165133_127 0 0 1](https://github.com/user-attachments/assets/f964c40c-6485-4514-8349-26b6390db028)
