### ISSUE TITLE
Request: apps section

### ISSUE THREAD

**Issue by BobHasNoSoul** [axewater/sharewarez#8]
i have several apps that could be easily shared in this and so far i have been remapping them by using obscure igdb ids to then modify them manually, can you at some point (non urgent) add a apps section that admins can map content to manually without the need to go through igdb?

thanks

**Comment by axewater** [comment]
this is a big wish of my own. the point im struggling with is getting a good database to scrape / API to use to get info on apps.
today i did introduce multi libraries support, with mplatform selection. I just didnt think about APPS and LINUX GAMES yet.
soon.,.. im keeping this issue open until resolved

**Comment by Bovive** [comment]
I suspect there are no great api sources to match applications like there is for media. If there was an application library I think it would have to be all manual entry by the user. The fields would need to be templated specifically for that library. So no scanning or anything with it.

**Comment by axewater** [comment]
cancelling this feature
