### ISSUE TITLE
Scanning Results in Error if Game Already Exists

### ISSUE THREAD

**Issue by Bovive** [axewater/sharewarez#85]
Running an automatic folder scan will result in a status of "Failed" for the scan if the games scanned already exist. The folder is also set as a "Failed" count.

Console output:

`Game already exists in database: Untitled Goose Game at D:\Test Games\PC\Untitled Goose Game
Failed to process game Untitled Goose Game: 'UPDATE_FOLDER_NAME'`

![Screenshot_23-10-2024_104754_127 0 0 1](https://github.com/user-attachments/assets/cc865b60-879d-4733-abd8-18ae290aa39d)

The expected behavior would be to skip games that already exist and not to result in an error. This must be a new bug. I tested this in v1.2.1 and this bug does not exist. 

I will also note that after deleting a game and then performing this scan, the game also elicits this error when rescanned. It does however add the game back to the library as expected.

**Comment by axewater** [comment]
i'm unable to reproduce this error on my end .. tested thoroughly. maybe I accidentally fixed it ?

**Comment by Bovive** [comment]
Looks like you fixed it with one of your recent commits. Confirmed working again!
