### ISSUE TITLE
Sugestion - :latest tag in docker image

### ISSUE THREAD

**Issue by daedric7** [axewater/sharewarez#9]
Will it be possible to have a :latest tag in docker hub? 

Makes updating easier anytime a new version is available.

**Comment by axewater** [comment]
another user also asked about this. this is something I have to learn and put into my workflow.
my next chance is the 1.2 release this weekend :)

**Comment by Bovive** [comment]
Is this working now? I used the :latest tag and it seemed to work.

**Comment by axewater** [comment]
its set as latest in the docker-compose.yml now
my docker knowledge is too limited to know if this is fixed or not?

**Comment by Bovive** [comment]
> its set as latest in the docker-compose.yml now my docker knowledge is too limited to know if this is fixed or not?

Have you created a new Docker release since 1.2.1? I'm using the :latest tag on mine and it has not offered an update since I first installed it.

**Comment by axewater** [comment]
docker updated to 1.4.4
update your own at any time:

docker-compose build
